apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: openshift-secondary-scheduler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
